### ISSUE TITLE
jest - " SyntaxError: Cannot use import statement outside a module"

### ISSUE THREAD

**Issue by zacharytyhacz** [gunn/pure-store#22]
howdy @gunn hope all is well for ya, all good over here my friend

I'm running tests with Jest where it's testing a React component that interacts with the store, and it's throwing this weird error which I've researched is related to babel? I'm not using babel or webpack, I'm using parcel which you recommended and I enjoy using

```
    /home/zac/Projects/project/app/application/client/node_modules/pure-store/react.js:14
    import * as React from 'react';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

    > 1 | import createStore from 'pure-store/react';
        | ^
      2 | 
      3 | export const feedbackStore = createStore([])
      4 | 

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1327:14)
      at Object.<anonymous> (store/feedback.ts:1:1)


```

this is my source store file:
```javascript
// notice '/react'
import createStore from 'pure-store/react';

export const feedbackStore = createStore([])
```

but what is super weird, is that if I remove the `/react` part from the import, it tests fine but throws weird Typescript errors that weren't showing up before:
```javascript
// no '/react'
import createStore from 'pure-store';

export const feedbackStore = createStore([])
```
 this is the typescript errors it throws this error when I use the exported `feedbackStore` to use `usePureStore` hook and is used just like it is shown on the readme:
```
app/components/Feedback/index.tsx:35:39 - error TS2339: Property 'usePureStore' does not exist on type 'PureStore<any[], any[]>'.

35     const [feedbacks] = feedbackStore.usePureStore();
                                         
```

source file where above is importing:
```javascript
import * as React from "react"
import { feedbackStore } from "../../../store/feedback";

...

export default () => {
    const [feedbacks] = feedbackStore.usePureStore();
    return (
      ...
    )
}

```

should the import package be `pure-store/react`? It's been working perfectly fine as `pure-store/react` and haven't had any problems until now running Jest, and the Typescript I not too sure how to solve since the readme shows to use it like this.

thanks Arthur any help would be great

--- also here's my jest config:
```javascript
module.exports = {
  roots: ["."],

  transform: {
    "^.+\\.tsx?$": "ts-jest"
  },

  moduleNameMapper: {
    "\\.(css|scss)$": "<rootDir>/tests/styleMock.js"
  },

  testRegex: "(/__tests__/.*|(\\.|/)(test|spec))\\.tsx?$",

  // Module file extensions for importing
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"]
};

```

**Comment by gunn** [comment]
Hmm, well the obvious part: the difference between `'pure-store'` and `'pure-store/react'` is that the latter has the `usePureStore ` hook in it. Since you are using that, you should use `import 'pure-store/react'`, and the error you get the other way is expected.

As for the main problem, I can't see enough to know but it sounds like an issue with the node / test-runner config. Unfortunately node has a different idea about what a module is than browsers do. A quick fix attempt you could try:

```json
transform: {
  "^.+\\.(j|t)sx?$": "ts-jest"
},
```

Otherwise if you create a repo with a minimal case I'll see if I can get it working there.

**Comment by zacharytyhacz** [comment]
Hey @gunn , thanks for the clarity. I tried that different `transform` regex and still shows same error.

I made minimal case repo of the issue here:

https://github.com/zacharytyhacz/pure-store-jest-bug

**Comment by gunn** [comment]
Nice, I got it using that repo. So the `pure-store` package ships with two copies - a fully compiled one with `require` calls, and a 'module' version with es6 imports. The packager should then select the correct version for it. For some reason node is picking the module version but not liking its import syntax.

You can fix this completely for yourself now by specifying the other version:

```js
import createStore from 'pure-store/dist/react'
```

Later I will see if it's safe to change the import syntax to something that's also node compatible to avoid this problem.

**Comment by zacharytyhacz** [comment]
Ah thanks arthur, that seems to work changing the import to `pure-store/dist/react` 
I'll just refactor my imports to this, no problem at all. 

thanks again - closing this issue
