### ISSUE TITLE
Any future plans?

### ISSUE THREAD

**Issue by andriytyurnikov** [gunn/pure-store#3]
This thing looks very attractive, thanks for sharing.
I wonder if you have any plans regarding computable state ( state derived by application of function against store ) and layer(s) for encapsulation of async and sync changes of state?

**Comment by andriytyurnikov** [comment]
Ok, both computed and periodic are trivial.
Man, this is great :) More examples, and it would save the world :)

**Comment by jamesiscool** [comment]
I would we interested in that as well 👍
