### ISSUE TITLE
Basic example not working 

### ISSUE THREAD

**Issue by shivekkhurana** [gunn/pure-store#7]
Hi @gunn ,

Pure-state looks dope. I was willing to replace redux with it in a small prod project. 
But the example you show doesn't seem to work. The state of the store gets updated, but the component is not re-rendered. Here is a fiddle showing the counter example. What am I doing wrong here ? Do I need to explicitly subscribe and unsubscribe ?

https://stackblitz.com/edit/react-zmpewg

**Comment by gunn** [comment]
Hi @shivekkhurana,

Yes, it's necessary to explicitly subscribe at least. I really need to expand the README with examples.
`pure-store`doesn't impose a single way of doing things, it gives you the fundamental pieces.

Here's how I do subscribing in my apps:

```javascript
const render = ()=> {
  ReactDOM.render(<App />, document.getElementById('root'))
}

store.subscribe(render)
render()
```

You could also use `forceUpdate` within a component e.g.:
``` javascript
class App extends React.Component {
  constructor() {
    store.subscribe(()=> this.forceUpdate())
  }
  //...
```
