### ISSUE TITLE
Readme mistake?

### ISSUE THREAD

**Issue by yairEO** [gunn/pure-store#9]
https://github.com/gunn/pure-store#bonus-storeforgetter--updaterforgetter

    // vs
    const addressStore = store.updaterFor(s=> s.user.profile.address)
    const addressUpdater = store.updaterFor(s=> s.user.profile.address)

You are calling `updaterFor` twice here and never use `storeFor`

**Comment by gunn** [comment]
@yairEO good catch, I'll fix that soon.
